src/posts/blogs/2022/0816_jett-intro.md

「EXCELテンプレートエンジンJETTの紹介」を追加しましたよろしくお願いいたします。

EXCELテンプレートエンジンJETTの紹介を追加

---

src/pages/msa.md
src/posts/msa/microprofile/cntrn06-mp-config.md
src/posts/msa/microprofile/cntrn08-mp-config3.md
src/posts/msa/microprofile/cntrn09-mp-openapi3.md

- 第9回 MicroProfile OpenAPI 3.0の新機能と既存機能の比較を新規に追加
- 第6回 お手軽便利MicroProfile Configの情報が誤っているところもついでに修正

add contents

---

src/pages/iot.md

IoT ランディングページ

---

src/posts/blogs/2022/1212_aws_all_certified.md

遅くなり申し訳ありません。12日目の記事を追加しました。よろしくお願いします。

アドカレ12日目記事追加

---

package-lock.json
package.json

Update 11ty v2

---

src/pages/frontend.md

プリレンダリングフレームワークをエッジ環境と独立させて最近の記事を追加しました。

Update frontend landing page

---

src/posts/blogs/2023/0807_llm_chat_model.md

2023/08/07掲載用の記事を作成いたしました。
レビューをお願いいたします。
一応、補足ですが今回利用している学習データ「名大会話コーパス」について
ライセンス「[クリエイティブ・コモンズ 表示-非営利-改変禁止 4.0 国際ライセンス](https://creativecommons.org/licenses/by-nc-nd/4.0/deed.ja)」があります。
こちら中身を見たところ、非営利かつ改変していなければ問題ないと認識しています。
改変の部分がネックなのですがどうやらフォーマットの改変は問題はなく、他のブログ（[この記事](https://qiita.com/gacky01/items/26cd642731e3eddde60d)や[この記事](https://economylife.net/gpt-talking-fine-tune/)）や
[対話ロボットに関する論文](https://hai-conference.net/proceedings/HAI2022/pdf/P-32.pdf)でも使用されているようですので、問題ないと判断して実験したままで載せています。
何か問題がある場合はご連絡いただければ幸いです。
よろしくお願いいたします。

add 2023-08-07 掲載用記事の作成

---

src/_includes/home.njk
src/_includes/post.njk

chore: delete event announcements

---

src/posts/blogs/2023/0614_gpt-function-calling-intro.md

OpenAI のChat APIの最新バージョンに追随するように記事を修正しました。

update blog to latest OpenAI API

---

src/posts/blogs/2023/1201_vuetify3-datatable.md

アドベントカレンダー(12/1) : Vuetify3 Data tables component

---

src/posts/blogs/2023/1209_jetbrains-ai-assistant-intro.md
src/posts/blogs/2023/1210_jetbrains-ai-assistant-intro.md

Introduced a new blog post discussing various features of JetBrains' AI assistant. The blog details useful aspects such as code generation, refactor suggestions, problem detection, and commit message generation. It also introduces creating custom prompts.

feat: Add new blog post about JetBrains AI assistant

---

deno.json
deno.lock
src/_components/PostList.tsx
src/_components/SocialPlugins.njk
src/_includes/layouts/advent.njk
src/_includes/layouts/base.njk
src/_includes/layouts/home.njk
src/_includes/layouts/post.njk
src/_includes/layouts/season.njk
src/_includes/styles/_post.pcss
src/css/style.css
src/js/preact/recommendation.client.tsx

Refactored the styling from custom CSS to Tailwind CSS classes for better maintainability. Additionally, replaced the inline JavaScript implementation for rendering social plugins with a more modular nunjucks component, improving code readability and reusability. The preact version was also updated for better performance and reliability.

Google SEO Improvement(Lighthouse)

---

src/_data/meta.ts
src/_includes/layouts/post.njk
src/js/preact/toc.client.tsx
src/posts/blogs/2023/1209_jetbrains-ai-assistant-intro.md

This update adds functionality to display an image in the table of contents section of blog posts. Additional properties (path, imageEnabled, imageUrl) were included in the Toc function, and conditional rendering was applied for the image. Changes also involve the render method and the modifications in the post template file to pass the necessary values.

feat: Add blog image on sidebar area if needed.

---

src/pages/frontend.md
src/posts/blogs/2024/0207_nuxt3-unit-testing-mount.md

A new blog post has been added to the 'posts' directory. The post focuses on setting up the Nuxt3 test utility library and writing unit tests for Nuxt3, particularly mounting test components. Future posts on this topic will delve further into making mocks in unit tests.

feat: Add new blog post for Nuxt3 unit testing

---

deno.json
src/posts/blogs/2024/0221_aws-lambda-llrt-intro.md

A new blog post has been added that covers the use of a new JavaScript runtime for AWS Lambda called LLRT. This post includes information on how to prepare a Lambda function, how to deploy the Lambda using AWS CDK, and also compares the performance of LLRT with the Node.js runtime on Lambda.

feat: Add new blog post about using AWS Lambda LLRT

---

src/posts/blogs/2024/0307_electron-webcontentsview.md
src/posts/blogs/2024/0310_sst-v3-intro.md

Extensive details about usage, setup, Lambda function creation, resource definition with SST's component, deployment with SST, and time efficiency are explained thoroughly in the post. Also includes comparison of deployment time between AWS CDK-based SST v2 and SST v3.

SST v3 blog

---

src/posts/blogs/2024/0315_pygame_boid.md

2024-03-15 掲載用記事の作成：PyGameでボイドモデルのシミュレーションをしよう

---

src/posts/blogs/2024/0421_openai-file-search-intro.md

Added a new blog post about the use of the File Search feature in the OpenAI's Assistants API. The post details how to create and manage a Vector Store, tie it with an assistant, fetch data from it, and handle costs with expiration policies among other aspects. This comes after recent updates to the Assistants API.

feat: Add OpenAI API blog post about File Search feature

---

src/posts/blogs/2024/0620_after_jjug_spring-mp.md

twitterの案内分には以下のようなコメントを入れていただけると助かります
> セッション終了後にいただいた質問をブログの形でまとめて回答させていただきます

JJUG CCC 2024 Spring 登壇後記 - Spring Boot vs MicroProfile セッションの補足と訂正

---

src/_components/SummerBanner2024.tsx

イベントバナータイトル修正(予告 -> 開催中)

---

src/posts/blogs/2024/0808_openapi-generator-constraints.md

直前過ぎてて申し訳ないです。  
予定していたものと大きくテーマが変わりましたが、レビューをお願いいたします。

ほんの少しだけOpenAPI Generatorを拡張してみません？

---

src/pages/frontend.md
src/posts/typescript-intro/introduction-to-typescript-for-java-engineer_index.md
src/posts/typescript-intro/introduction-to-typescript-for-java-engineer_other-basic-type.md
src/posts/typescript-intro/introduction-to-typescript-for-java-engineer_primitive-type.md

Java技術者向けのTypeScript入門記事（第4回）を作成したのでレビューお願いします。
当PRに含まれるページは9/11の公開を想定しています。
* introduction-to-typescript-for-java-engineer_index.md: リンクを修正　※リンクの修正だけなので日付は変更していません。
* introduction-to-typescript-for-java-engineer_primitive-type.md: リンクを修正　※リンクの修正だけなので日付は変更していません。
* introduction-to-typescript-for-java-engineer_other-basic-type.md: 今回追加予定の記事
* pages/frontend.md: 修正していません。こちらで修正して良ければ今後修正に含めます。

Javaエンジニアが始めるTypeScript入門（第4回：その他の基本型）

---

src/posts/blogs/2024/0914_openai-filesearch-tuning.md

Introduces a detailed guide on analyzing and tuning results from OpenAI's File Search tool using their Assistants API. Covers initial setup, configuring chunk settings, adjusting search parameters, and interpreting responses, providing practical examples with Python code snippets.

feat: Add blog post on tuning OpenAI File Search

---

src/posts/blogs/2024/1007_openai-realtime-api-intro.md
src/posts/blogs/2024/1009_openai-realtime-api-intro.md

Introduced a new blog post detailing the recently released OpenAI Realtime API. The blog explains how to set up real-time voice interactions using WebSockets in a CLI-based implementation. It includes code snippets and practical tips for using the API effectively.

feat: Add blog post introducing OpenAI Realtime API

---

src/pages/frontend.md
src/posts/typescript-intro/introduction-to-typescript-for-java-engineer_function.md
src/posts/typescript-intro/introduction-to-typescript-for-java-engineer_index.md

Java技術者向けのTypeScript入門記事（第7回）を作成したのでレビューお願いします。
当PRに含まれるページは10/9の公開を想定しています。
* pages/frontend.md: リンクを追記
* introduction-to-typescript-for-java-engineer_index.md: リンクを追記　※日付は変更していません。
* introduction-to-typescript-for-java-engineer_function.md: 今回追加予定の記事

Javaエンジニアが始めるTypeScript入門（第7回：関数）　記事追加

---

.devcontainer/Dockerfile
.devcontainer/compose.yaml
.devcontainer/devcontainer.env
.devcontainer/devcontainer.json
.gitignore
.vscode/launch.json
.vscode/tasks.json

リポジトリへの追加機能です。
- `.vscode/{launch.json,tasks.json}` の追加
- lintでカレントで開いているファイルの校正を実行できるようにしました
- launch.jsonでdeno serveをChromeで開くようにできました
- `.devcontainer` の追加
- deno環境を定義してあります
- リポジトリをcloneしてdevcontainerで開けば、denoのインストール不要でそのまま記事に着手できます

機能追加: .vscode, .devcontainer

---

src/posts/blogs/2024/1101_aws_cloudshell_credentials.md
src/posts/blogs/2024/1105_aws_cloudshell_credentials.md

記事執筆（CloudShellで資格情報取得）

---

src/posts/blogs/2024/1219_ai_boid_simulation.md

2024/12/19（木）掲載予定の記事を作成いたしました。
お手数をおかけしますが、ご確認のほどよろしくお願いいたします。

【アドカレ19日目】ローカルLLMを使ったボイドシミュレーション（llama.cpp、llama-cpp-python）

---

src/posts/blogs/2024/1220_asp-dotnet-core-blazor.md

@kondoumh さん
アドカレ20日目の記事を執筆しました。  
レビューをお願いいたします。

【アドカレ20日目】はじめてのASP.NETCoreBlazorアプリ（概要編）

---

src/posts/blogs/2025/0122_perplexity-sonar-intro.md

This new post explains Perplexity's Sonar API announced on January 21, 2025. It introduces its features, pricing, and usage through Python examples, comparing "sonar" and "sonar-pro" models with detailed insights.

feat: Add blog post introducing Perplexity's Sonar API

---

lint.ts

lint実行時に、特定のシンタックスを校正対象から除外できるようにしました。

---

src/posts/robotics/choreonoid/choreonoid_part1.md

記事『[Choreonoidで始めるロボットシミュレーション（その1）](https://developer.mamezou-tech.com/robotics/choreonoid/choreonoid_part1/)』　にて紹介したコードを共有しているGitHubリポジトリが諸事情により変更となったためURLを変更しました。
その他の変更点はありません。

諸事情によるGitHubリポジトリURLの変更

---

src/posts/blogs/2025/0226_langmem-intro.md

Introduce a new blog post detailing the LangMem SDK, its long-term memory management capabilities, and how to use its APIs. This includes examples of integrating LangMem with LLMs for improved contextual interactions.

feat: add LangMem overview and usage blog post

---

src/posts/blogs/2025/0313_clickhouse-rag.md

分析用データベースエンジンであるClickHouseのチュートリアル的な記事です

3月13日投稿予定記事_commit

---

src/posts/blogs/2025/0319_openai-responses-api-filesearch.md

Add a comprehensive blog post detailing the formal release of OpenAI's Responses API and its built-in File Search tool. Includes implementation examples, Vector Store setup, metadata filtering, and integration insights for developers.

feat: add new blog post on OpenAI Responses API and File Search

---

src/pages/dev-env.md
src/posts/blogs/2023/0219_esp-idf-vsc-extension.md
src/posts/blogs/2025/0503_esp-idf-vsc-extension-2.md
src/posts/blogs/2025/0506_esp-idf-vsc-extension-3.md

IDF Component ManagerとKconfig設定でハマった話（VSCode＋ESP-IDF拡張機能）

---

src/posts/blogs/2024/1113_aws-appsync-events.md
src/posts/blogs/2025/0507_appsync-events-datasource-integration.md

Introduce a comprehensive blog post detailing AWS AppSync Events' new datasource integration functionality. The post covers integration examples using DynamoDB and Lambda, along with step-by-step implementation and verification using CDK.

feat: add blog on AppSync Events datasource integration

---

src/posts/blogs/2025/0728_csharp_linq.md

.NET系記事の第二段として、便利だけど分かりづらくて苦戦しやすいLINQの解説記事を作成しました。

C# LINQのまとめ記事を作成
